name: KAT
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.5
  - cellpose=4.0.6
  - matplotlib=3.9.2
  - matplotlib-inline=0.1.7
  - numba=0.61.2
  - numpy=2.1.0
  - numpydoc=1.9.0
  - pandas=2.2.2
  - tqdm=4.66.5
  - pillow  # for PIL.Image