"""PipelineState for the preprocess web GUI.

Mirrors the fields of preprocess_gui.py's PipelineState but is JSON-serializable
so it can persist to session.json between page reloads and be round-tripped
through the Flask endpoints.
"""

import json
import os
import threading
from dataclasses import asdict, dataclass, field, fields
from typing import Any


@dataclass
class PipelineState:
    # Paths
    global_dir: str = ""
    frames_dir: str = ""
    masks_dir: str = ""
    save_path: str = ""
    all_frames: list = field(default_factory=list)
    all_masks: list = field(default_factory=list)

    # Cellpose
    flow_threshold: float = 0.975
    cellprob_threshold: float = -4.0
    niter: int = 3000
    diameter: int = 26
    frame_idx: int = 0

    # Save interval
    save_interval: int = 10

    # Shift
    shift_frame_idx: int = 1
    shift_xy: tuple = (0, 0)

    # Max distance
    max_distance: float = 30.0

    # ROI
    radius: int = 2000
    y_shift: int = 0
    x_shift: int = 0

    # Duplicate / trajectories
    grace_period: int = 3

    # Post-analysis
    f0_frame: int = 1
    stim_frames: str = ""

    def to_dict(self) -> dict:
        d = asdict(self)
        d["shift_xy"] = list(self.shift_xy)
        return d

    def update(self, patch: dict) -> None:
        valid = {f.name for f in fields(self)}
        for k, v in patch.items():
            if k not in valid or v is None:
                continue
            if k == "shift_xy":
                v = tuple(v)
            setattr(self, k, v)


class SessionStore:
    """Holds the single PipelineState and persists it to session.json."""

    def __init__(self, path: str):
        self.path = path
        self.lock = threading.Lock()
        self.state = PipelineState()
        # Non-serialised runtime caches
        self.temp_segmentation = None  # numpy array from last Cellpose run
        self.load()

    def load(self) -> None:
        if not os.path.isfile(self.path):
            return
        try:
            with open(self.path) as f:
                data = json.load(f)
            self.state.update(data)
        except Exception:
            pass

    def save(self) -> None:
        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        tmp = self.path + ".tmp"
        with open(tmp, "w") as f:
            json.dump(self.state.to_dict(), f, indent=2)
        os.rename(tmp, self.path)

    def apply_patch(self, patch: dict) -> dict:
        with self.lock:
            self.state.update(patch)
            self.save()
            return self.state.to_dict()

    def snapshot(self) -> dict:
        with self.lock:
            return self.state.to_dict()


def parse_config_txt(path: str) -> dict:
    """Parse analysis/config.txt (generated by run_processes.sh) into a patch
    dict compatible with PipelineState. Unknown keys are ignored."""
    if not os.path.isfile(path):
        return {}
    key_map = {
        "FLOW_THRESHOLD": ("flow_threshold", float),
        "CELLPROB_THRESHOLD": ("cellprob_threshold", float),
        "NITER": ("niter", int),
        "DIAMETER": ("diameter", int),
        "MAX_DISTANCE": ("max_distance", float),
        "GRACE_PERIOD": ("grace_period", int),
        "RADIUS": ("radius", int),
        "RADIUS_Y": ("y_shift", int),
        "RADIUS_X": ("x_shift", int),
        "SHIFT_FRAME": ("shift_frame_idx", int),
        "SAVE_INTERVAL": ("save_interval", int),
    }
    patch: dict[str, Any] = {}
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if "=" not in line or line.startswith("["):
                    continue
                k, v = line.split("=", 1)
                k = k.strip()
                v = v.strip()
                if k == "SHIFT_XY":
                    try:
                        parts = v.split()
                        if len(parts) == 2:
                            patch["shift_xy"] = (int(parts[0]), int(parts[1]))
                    except ValueError:
                        pass
                elif k in key_map:
                    name, cast = key_map[k]
                    try:
                        patch[name] = cast(v)
                    except ValueError:
                        pass
    except Exception:
        pass
    return patch
